name: chat_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  firebase_auth: ^0.16.1
  image_picker: ^0.6.7+2
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.13.7
  intl: ^0.16.1
  google_sign_in: ^4.5.1
  cached_network_image: ^2.2.0+1
  firebase_messaging: ^6.0.16
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.8
  flutter_local_notifications: 1.4.0
  photo_view: ^0.9.2

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
